import type { Metadata } from "next";
import "./globals.css";
import ReactLenis from "lenis/react";
import Navbar from "./Components/Navbar";
import Footer from "./Components/Footer";

export const metadata: Metadata = {
  title: "Abuzar Ali",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className="antialiased"
      >
        <ReactLenis root options={{ lerp: 0.1, duration: 1.5, smoothWheel: true }}>
          <Navbar />
          <main className="pt-20">
            {children}
          </main>
          <Footer />
        </ReactLenis>
      </body>
    </html>
  );
}
