import { CloudDrizzle, ListTodo, School, Store,  } from "lucide-react";

export const PROJECTS = [
  {
    id: 1,
    title: "Dummy Shop",
    description: "A modern eCommerce platform  Dummy Shop.",
    tech: ["Next.js", "JavaScript", "React",  "Tailwind" , "Redux"],
    github : "https://github.com/abuzar-ali1/dummy-shop",
    liveLink: "https://dummy-shop-eosin.vercel.app",
    image: "/Images/dummy_shop.png", 
    size: "md:col-span-2 md:row-span-2",
    icon: Store,
  },
  {
    id: 2,
    title: "Fresh Cart",
    description: "Used Open Source API for this Simple store with Add to cart and Authentication integration.",
    tech: ["Redux", "JavaScript", "React",  "Tailwind"],
    github : "https://github.com/abuzar-ali1/Eccomerce-react.js",
    liveLink: "https://eccomerce-react-js-iota.vercel.app",
    image: "/Images/fresh_cart.png",
    size: "md:col-span-1 md:row-span-1",
    icon: Store,
  },
  {
    id: 3,
    title: "Weather App",
    description: "Developed a weather app integrating a real-time weather API to display dynamic forecasts",
    tech: ["Next.js", "TypeScript", "React",  "Tailwind" , "ReactQuery"],
    github: "https://github.com/abuzar-ali1/Weather-App",
    liveLink: "https://weather-app-mauve-seven-88.vercel.app",
    image: "/Images/weather_app.png",
    size: "md:col-span-1 md:row-span-1",
    icon: CloudDrizzle,
  },  {
    id: 4,
    title: "Google Classroom Clone",
    description: "Developed a classroom management web app featuring CRUD operations for assignments with real-time state persistence via localStorage.",
    tech: ["Next.js", "React", "Redux", "JavaScript",  "MUI"],
    github: "https://github.com/abuzar-ali1/Google-Classroom" ,
    liveLink: "https://google-classroom-hazel.vercel.app",
    image: "/Images/google_class.png",
    size: "md:col-span-1 md:row-span-1",
    icon: School,
  },  {
    id: 5,
    title: "Modern Todo App",
    description: "Developed a weather app featuring add/edit/delete via modal form, search, filters (All/Active/Completed), and smooth animated list transitions",
    tech: ["Next.js", "JavaSript", "React",  "Mui" , "Framer Motion"],
    github:"https://github.com/abuzar-ali1/Modern-Todo-App",
    liveLink: "https://modern-todo-tau.vercel.app",
    image: "/Images/todo_app.png",
    size: "md:col-span-1 md:row-span-1",
    icon: ListTodo,
  },  {
    id: 6,
    title: "Organio Shop",
    description: "Built an E-commerce management website , features functions like add to cart , sign in sign up and . Implemented responsive using Bootstrap , dynamic routing for multi pages.",
    tech: ["HTML",   "CSS" ,"JavaScript", "Bootstrap"],
    github: "https://github.com/abuzar-ali1/Home-5---Organio-Website",
    liveLink: "https://capstone-3-psi.vercel.app",
    image: "/Images/organio.png",
    size: "md:col-span-1 md:row-span-1",
    icon: Store,
  },
];