# Generated by Django 6.0.4 on 2026-04-19 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_project_image_url_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='display_type',
            field=models.CharField(default='standard', max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='icon_name',
            field=models.CharField(default='Code', help_text='e.g., Github, Store, CloudDrizzle, School', max_length=50),
        ),
    ]
